apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-8" # namespaces(-9)가 먼저 확실히 뜬 뒤 실행되도록 한 단계 뒤로
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/urineun-jigeum-bildeujung/gitops.git
    targetRevision: main
    path: platform/05-rbac/manifests
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
