# kafka-operator(40번)가 먼저 준비된 뒤, 실제 Kafka 클러스터(브로커) CR을 적용.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/urineun-jigeum-bildeujung/gitops.git
    targetRevision: main
    path: platform/50-kafka-cluster/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
