apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-crd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    # 1.13.0 OCI manifest digest 확인값:
    # sha256:3176c3ac16914cd033ac17fea9428d5f21170e1347d9cd91ae43a34836dfa5a6
    repoURL: public.ecr.aws/karpenter
    chart: karpenter-crd
    targetRevision: "1.13.0"
    helm:
      releaseName: karpenter-crd
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
