{{- if not (or .Values.canary.enabled .Values.blueGreen.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-service.name" . }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "generic-service.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "generic-service.name" . }}
      containers:
        - name: {{ include "generic-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
            {{- if .Values.mtls.enabled }}
            - containerPort: 8443
              name: mtls
            {{- end }}
          env:
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
            {{- include "generic-service.mtlsEnv" . | nindent 12 }}
          {{- if .Values.mtls.enabled }}
          volumeMounts:
            - name: mtls-cert
              mountPath: /etc/mtls
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.mtls.enabled }}
      volumes:
        - name: mtls-cert
          secret:
            secretName: {{ include "generic-service.name" . }}-mtls-cert
      {{- end }}
{{- end }}
