{{- if eq (include "generic-service.autoscalingMode" .) "hpa" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ default (include "generic-service.name" .) .Values.autoscaling.resourceName }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "generic-service.scaleTargetApiVersion" . }}
    kind: {{ include "generic-service.scaleTargetKind" . }}
    name: {{ include "generic-service.name" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- with .Values.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
