{{- if .Values.podDisruptionBudget.enabled }}
{{- if and (ne .Values.podDisruptionBudget.minAvailable nil) (ne .Values.podDisruptionBudget.maxUnavailable nil) }}
{{- fail "podDisruptionBudget: set only one of minAvailable or maxUnavailable" }}
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ default (printf "%s-pdb" (include "generic-service.name" .)) .Values.podDisruptionBudget.name }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  {{- if ne .Values.podDisruptionBudget.minAvailable nil }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- if .Values.podDisruptionBudget.selectorLabels }}
      {{- toYaml .Values.podDisruptionBudget.selectorLabels | nindent 6 }}
      {{- else }}
      {{- include "generic-service.selectorLabels" . | nindent 6 }}
      {{- end }}
{{- end }}
